### ISSUE TITLE
A better example for recipe

### ISSUE THREAD

**Issue by shellstroem** [TurkuNLP/register-annotation-docs#16]

**Comment by shellstroem** [comment]
https://www.icedjems.com/2012/09/banana-trifle/

**Comment by spyysalo** [comment]
I wonder if https://wholefully.com/next-day-turkey-vegetable-soup/ could actually serve as an example of a recipe + narrative hybrid..?

**Comment by shellstroem** [comment]
Well, yes that surely is some kind of a hybrid. Perhaps Narrative blog + Recipe?
