### ISSUE TITLE
Q: e-library offering books for free

### ISSUE THREAD

**Issue by shellstroem** [TurkuNLP/register-annotation-docs#23]
How could we classify an e-library that offers books for free? like this one here (FIY 'kutub' in Arabic means 'books'): https://www.kutub.info/library/book/21784

The texts on the site are probably describing the books with the intent to get the potential readers interested in them and thus they are most likely book blurbs and would be classified as Description with intent to sell. This is of course a bit contradictory, since the books are not sold, but I'd probably annotate them as described.

**Comment by annsaln** [comment]
edited IP-ds
