### ISSUE TITLE
Q: Instructions that are not step-by-step

### ISSUE THREAD

**Issue by fshdnc** [TurkuNLP/register-annotation-docs#37]
Q: In general, what do we do with instructions that are not step-by-step? For example
(a) Instructions on course assignments, including the requirements, submission details, potential references. -> HI-oh?
(b) Official documents including instructions and decisions from the government -> HI-oh?
(c) Course material on how to come up with a title for a research article, how to write a summary -> IN-oi or HI-oh?
(d) Hybrid: documentation of experiences of losing weight, as well as for instructions on how to do that (not step by step), including a list of food to eat and when to eat, and how to exercise) -> NA-nb & HI-oh?

A: If the instructions are explicit and objective, I'd still annotate them as HI-oh in general, maybe as a hybrid if there are features of another register.
a: This I'd probably annotate as HI-oh
b: This maybe HI-oh + IN-oi, if it's a report of some sort
c. This again probably HI-oh + IN-oi, if it's a piece of course material
d. If the advice is from a personal perspective, I'd probably annotate it as OP-av rather than HI-oh. in general, HI-oh is objective, neutral instructions. Otherwise, this annotation looks good to me.

**Comment by annsaln** [comment]
edited HI-oh
